### ISSUE TITLE
未启用严格模式，貌似 babel-plugin-mobx-deep-action 插件体现不出作用吧

### ISSUE THREAD

**Issue by cheft** [xiaoyyang123/react-mobx-boilerplate#1]
发现  babel-plugin-mobx-deep-action 在严格模式下并无作用

你好，我最近也在搞 mobx ，有机会希望可以交流一下。

**Comment by cheft** [comment]
终于解决了，在严格模式下用这段配置：
```js
{
  "passPerPreset": true,
  "presets": [
    {
      "plugins": ["transform-regenerator"]
    },
    {
      "plugins": ["mobx-deep-action"]
    },
    {
      "plugins": ["transform-decorators-legacy", "transform-class-properties"]
    },
    "react-native"
  ]
}

```

**Comment by sealzrt** [comment]
我的怎么不好使啊, 用了你的配置就报别的错误, 请问 你的配置现在还好使么?
现在我的配置是
{
  "plugins": [
    "transform-regenerator",
    "mobx-deep-action",
    "transform-decorators-legacy",
    "transform-class-properties"
  ],
  "presets": [
    "react-app"
  ]
}
